# Description: etcd
licenses(["notice"])

package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "etcd_provider_test.yaml",
])

cc_library(
    name = "mock_etcd_provider",
    hdrs = ["mock_etcd_provider.h"],
)
