name: CI
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
jobs:
  compile-with-bazel:
    runs-on:
      group: Default
      labels: trpc-cpp-plugins-ci
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
           ./clean.sh
           bazel test //trpc/...
